/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    container: {
      center: true,
      padding: '24px',
    },
    extend: {
      colors: {
        // Vintage-editorial palette sampled from the Nava Dishe deck's own
        // artwork (warm cream paper, navy ink, burnt-orange accent) rather
        // than the earlier blue corporate system.
        surface: '#F9EBD2',
        'surface-dim': '#E3CB8E',
        'surface-bright': '#FFFDF7',
        'surface-container-lowest': '#FFFDF7',
        'surface-container-low': '#F3E6C8',
        'surface-container': '#EFDFB8',
        'surface-container-high': '#EAD6A3',
        'surface-container-highest': '#E3CB8E',
        'on-surface': '#14233F',
        'on-surface-variant': '#5A5544',
        'inverse-surface': '#14233F',
        'inverse-on-surface': '#F7ECD6',
        outline: '#8A8368',
        'outline-variant': '#D9CBA3',
        primary: '#14233F',
        'on-primary': '#FBF3E1',
        'primary-container': '#1B2C4D',
        'on-primary-container': '#F7ECD6',
        'inverse-primary': '#E3CB8E',
        secondary: '#8A4A12',
        'on-secondary': '#ffffff',
        'secondary-container': '#E2790F',
        'on-secondary-container': '#4A2400',
        tertiary: '#7f2700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a73600',
        'on-tertiary-container': '#ffcab9',
        error: '#B3261E',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#1B2C4D',
        'primary-fixed-dim': '#14233F',
        'on-primary-fixed': '#F7ECD6',
        'on-primary-fixed-variant': '#F7ECD6',
        'secondary-fixed': '#F6DAB3',
        'secondary-fixed-dim': '#E2790F',
        'on-secondary-fixed': '#4A2400',
        'on-secondary-fixed-variant': '#4A2400',
        background: '#F9EBD2',
        'on-background': '#14233F',
        'surface-variant': '#E3CB8E',
        success: '#3F7D4A',
      },
      fontFamily: {
        display: ['"Bodoni Moda"', 'serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
      },
      maxWidth: {
        container: '1280px',
      },
      boxShadow: {
        level2: '0 4px 20px rgba(20, 35, 63, 0.12)',
        level3: '0 12px 32px rgba(20, 35, 63, 0.22)',
      },
    },
  },
  plugins: [],
};
